### ISSUE TITLE
Implement Uploading of Resources to GitServer

### ISSUE THREAD

**Issue by shresthagrawal** [ununu-p2p/ink-desktop#23]
With the latest pull request of the als parser, we can get the list of resource files for a project.
* [ ] Create a resource dir and put all the resource files, on the start of the Project.
* [ ] On project status check for the change in resource files and show the diff
* [ ] On every commit check, copy if anything changed to the resource dir
* [ ] On git pull modify the Als files for the new resource location.

**Comment by falafeljan** [comment]
@shresthagrawal, has this been closed by #36?

**Comment by shresthagrawal** [comment]
yes @falafeljan
