### ISSUE TITLE
don't use `ink.json` project path when interacting with projects

### ISSUE THREAD

**Issue by falafeljan** [ununu-p2p/ink-desktop#40]
just rely on the path/UUIDs specified in the app's local project store. happens within the meta file class:

https://github.com/ununu-p2p/ink-desktop/blob/9632d44f50b231dc6ec0e558903f27ba8899bb0b/lib/ink-file.js#L12-L17

**Comment by shresthagrawal** [comment]
@falafeljan I will look into the issue!

**Comment by shresthagrawal** [comment]
solve by #48
