### ISSUE TITLE
Show the Git Graph

### ISSUE THREAD

**Issue by shresthagrawal** [ununu-p2p/ink-desktop#7]
Show the git log in a git tree visual. Some inspiration could be taken from the [Ungit](https://github.com/FredrikNoren/ungit) project . 

![Sample](https://i2.wp.com/seanmacentee.com/wp-content/uploads/2013/11/ungit.jpg)

**Comment by blushi** [comment]
Added the back-end label since the back-end needs to provide various structured info to the front-end so it can build the git graph.

**Comment by falafeljan** [comment]
after talking to @shresthagrawal i've decided to move this back to to-do and rather focus on the overall backend performance.

all existing logic is contained in the `CommitGraph` component:
https://github.com/ununu-p2p/ink-desktop/blob/7b7c376b9514736937f743c5f590ceee01b01bde/renderer/components/CommitGraph.js#L125

we basically traverse the given graph object and create a linear list of commits (nodes), all connected by the leftmost edges. if a node contains nodes on its own (a branching), they are rendered with an indentation.

the `Line`, `BranchLine`, and `MergeLine` components display the branching via a CSS-only solution (good performance) achived by applying CSS transformations:
https://github.com/ununu-p2p/ink-desktop/blob/7b7c376b9514736937f743c5f590ceee01b01bde/renderer/components/CommitGraph.js#L28-L52

to resolve this issue, we'd need to create a proper, flexible graph that...
* shows commits in historical order
* can display an arbitrary nummer of branches
* can display merges (or merge commits)
* extends the current layout by using a CSS-only solution, use SVG, or even a library such as [d3](https://d3js.org/)

**Comment by shresthagrawal** [comment]
@falafeljan does prachi's work already tackle everything mentioned above?

**Comment by falafeljan** [comment]
i thnk so, yes! it's not vertical but horizontal, but otherwise, we can display a graph now!

**Comment by falafeljan** [comment]
closed by #60.
